# Generated by Django 3.0.3 on 2020-03-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_auto_20200315_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='do_show_summary',
            field=models.BooleanField(default=True),
        ),
    ]
