# Generated by Django 3.0.3 on 2020-05-17 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0006_auto_20200515_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created date'),
        ),
        migrations.AddField(
            model_name='mood',
            name='modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='modified date'),
        ),
    ]
