# Generated by Django 3.0.3 on 2020-03-21 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20200310_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, verbose_name='modified date')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('summary', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'group',
            },
        ),
        migrations.CreateModel(
            name='UserMoodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reader', models.BooleanField(default=False)),
                ('mood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mood_groups.MoodGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'verbose_name': 'user_mood_group',
            },
        ),
    ]
