# Generated by Django 3.0.3 on 2020-03-29 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mood_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodgroup',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='moodgroup',
            name='modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='modified date'),
        ),
    ]
