# Generated by Django 3.0.3 on 2020-05-17 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mood_groups', '0003_moodgroupinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodgroupinvitation',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created date'),
        ),
        migrations.AddField(
            model_name='moodgroupinvitation',
            name='modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='modified date'),
        ),
        migrations.AddField(
            model_name='usermoodgroup',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created date'),
        ),
        migrations.AddField(
            model_name='usermoodgroup',
            name='modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='modified date'),
        ),
        migrations.AlterField(
            model_name='moodgroup',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='moodgroup',
            name='modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='modified date'),
        ),
    ]
